MusicApp/MusicApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

MusicApp/music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name="index"),

    # /music/712/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),

    # music/album/add
    url(r'album/add$', views.AlbumCreate.as_view(), name="album-add"),

    # music/album/2
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name="album-update"),

    # music/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name="album-delete"),



]

MusicApp/music/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Album (models.Model):

    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):

    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

MusicApp/music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Album

class IndexView (generic.ListView):

    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):

        return Album.objects.all()

class DetailView (generic.DetailView):

    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):

    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):

    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):

    model = Album
    success_url = reverse_lazy('music:index')

MusicApp/music/templates/music/album_confirm_delete.html
{%extends 'music/base.html'%}
{%block title%} deleting album{%endblock%}
{% block body%}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{%endblock%}

MusicApp/music/templates/music/album_form.html
{% extends 'music/base.html'%}
{% block title%} add a new album{% endblock%}
{%block albums_active%}active{%endblock%}
{% block body%}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token%}
                            {% include 'music/form-template.html'%}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock%}

MusicApp/music/templates/music/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Home</title>

        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script> -->
        {% load staticfiles %}

        <link rel="stylesheet" href="{% static 'music/bootstrap-3.3.7-dist/css/bootstrap.min.css'%}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="{% static 'music/bootstrap-3.3.7-dist/js/bootstrap.min.js'%}"></script>

        <link rel="stylesheet" href="{% static 'music/style.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <!-- logo and collapse button -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top_nav_bar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'music:index'%}">Musica</a>
                    </div>

                    <!-- items -->
                    <div class="collapse navbar-collapse" id="top_nav_bar">
                        <ul class="nav navbar-nav">
                            <li class="active">
                                <a href="{% url 'music:index'%}">
                                    <span class="glyphicon glyphicon-cd" aria-hidden="True"></span>&nbsp; Albums
                                </a>
                            </li>
                            <li class="">
                                <a href="#">
                                    <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                                </a>
                            </li>
                        </ul>
                        <form class="navbar-form navbar-left" role="search" method="get" action="#">
                            <div class="form-group">
                                <input type="text" class="form-control" name="q" value=""/>
                            </div>
                            <button type="submit" class="btn btn-default"> search </button>
                        </form>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="{% url 'music:album-add'%}">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; add album
                                </a>
                            </li>
                            <li class="">
                                <a href="#">
                                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; logout
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
        </nav>
        {% block body %}
        {%endblock%}
    </body>
</html>

MusicApp/music/templates/music/detail.html
{%extends 'music/base.html'%}
{%block title%}Album details{%endblock%}

{%block body%}
    <img src="{{album.album_logo.url}}" height="200px" width="200px"/>
    <h1>{{album.album_title}}</h1>
    <h3>{{album.artist}}</h3>

        {%  for song in album.song_set.all %}
            {{song.song_title}}
            {% if song.is_favorite%}
                <img src="https://compgen.bio.ub.edu/image452&thumb=1" height="60px" width="60px"/>
            {% endif%}
            <br />
        {% endfor%}
{%endblock%}

MusicApp/music/templates/music/form-template.html
{% for field in form%}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10" >
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">
            {{ field.label_tag}}
        </label>
        <div class="col-sm-10">
            {{field}}
        </div>
    </div>
{% endfor%}

MusicApp/music/templates/music/index.html
{% extends 'music/base.html'%}
{%block body%}


    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">

                {% for album in all_albums%}
                     <div class="well">
                         <img src="{{album.album_logo.url}}" alt="{{album.album_title}} album logo" height="300px" width="300px">
                         <h2>{{album.album_title}}</h2>
                         <h3>{{album.artist}}</h3>
                         <a  class="btn btn-primary" href="{% url 'music:detail' album.id %}">view details</a>
                         <a  class="btn btn-danger" href="{% url 'music:album-delete' album.id %}">delete</a>
                         <a  class="btn btn-default" href="{% url 'music:album-update' album.id %}">update</a>

                     </div>
                {%endfor%}

        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock%}